name: Build and Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build Marauder binaries
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    strategy:
      matrix:
        arduino-board-fqbn:
        - esp32:esp32:esp32s2
        include:
          - arduino-boards-fqbn: esp32:esp32:esp32s2
            extra-arduino-cli-args: "--warnings all -zmuldefs"
        
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Install TFT_eSPI
        uses: actions/checkout@v2
        with:
          repository: justcallmekoko/TFT_eSPI
          ref: master
          path: CustomTFT_eSPI
          
      - name: Install LinkedList
        uses: actions/checkout@v2
        with:
          repository: ivanseidel/LinkedList
          ref: master
          path: CustomLinkedList
          
      - name: Install lv_arduino
        uses: actions/checkout@v2
        with:
          repository: lvgl/lv_arduino
          ref: master
          path: Customlv_arduino
          
      - name: Install JPEGDecoder
        uses: actions/checkout@v2
        with:
          repository: Bodmer/JPEGDecoder
          ref: master
          path: CustomJPEGDecoder
          
      - name: Install NimBLE-Arduino
        uses: actions/checkout@v2
        with:
          repository: h2zero/NimBLE-Arduino
          ref: master
          path: CustomNimBLE-Arduino
          
      - name: Install Adafruit_NeoPixel
        uses: actions/checkout@v2
        with:
          repository: adafruit/Adafruit_NeoPixel
          ref: master
          path: CustomAdafruit_NeoPixel
          
      - name: Install ArduinoJson
        uses: actions/checkout@v2
        with:
          repository: bblanchon/ArduinoJson
          ref: v6.18.2
          path: CustomArduinoJson
          
      - name: Install SwitchLib
        uses: actions/checkout@v2
        with:
          repository: justcallmekoko/SwitchLib
          ref: main
          path: CustomSwitchLib
          
      # Setup Test compile for Arduino
      - name: Build Marauder for Flipper Zero WiFi Dev Board
        uses: ArminJo/arduino-test-compile@v3.0.0
        with:
          sketch-names: esp32_marauder.ino
          #arduino-board-fqbn: esp32:esp32:esp32s2
          platform-url: https://github.com/espressif/arduino-esp32/releases/download/2.0.0-rc1/package_esp32_dev_index.json
          arduino-board-fqbn: ${{ matrix.arduino-board-fqbn }}
          extra-arduino-cli-args: ${{ matrix.extra-arduino-cli-args }}
          #extra-arduino-cli-args: "-w"
          #extra-arduino-lib-install-args: "-zmuldefs"
